package com.activiti.extension.oaf.constants;

public enum OAFApproverLevel {

	LEVEL1APPROVAL1,
	LEVEL1APPROVAL2,
	LEVEL2APPROVAL1,
	LEVEL2APPROVAL2,
	LEVEL3APPROVAL1,
	LEVEL4APPROVAL1,
	LEVEL5APPROVAL1,
	LEVEL6APPROVAL1,
	LEVEL7APPROVAL1
}
